Repository WildCodeSchool/orleans-0918-php-metiers-du-numerique, pull requests merged in 2018-12, with the labels that each got.

#52 Sprint02 us56
  assets/css/app.scss
  assets/images/WCS_400x400.jpg
  assets/images/elephpant_760_521-518x355.png
  src/Controller/LearningCenterController.php
  src/Entity/Job.php
  src/Entity/LearningCenter.php
  src/Form/LearningCenterType.php
  src/Migrations/Version20181128091914.php
  src/Migrations/Version20181130155355.php
  src/Repository/LearningCenterRepository.php
  symfony.lock
  templates/base.html.twig
  templates/learning_center/_delete_form.html.twig
  templates/learning_center/_form.html.twig
  templates/learning_center/edit.html.twig
  templates/learning_center/index.html.twig
  templates/learning_center/new.html.twig
  templates/learning_center/show.html.twig
Labels: Review by PO

#58 Probleme d'affichage du a la BDD
  src/Migrations/Version20181121095902.php
  src/Migrations/Version20181121103930.php
  src/Migrations/Version20181122155201.php
  src/Migrations/Version20181122181103.php
  src/Migrations/Version20181122183247.php
  src/Migrations/Version20181127102743.php
  src/Migrations/Version20181127103703.php
  src/Migrations/Version20181128104618.php
  src/Migrations/Version20181128173743.php
  src/Migrations/Version20181129091739.php
  src/Migrations/Version20181130153042.php
Labels: Review by PO

#59 S02 us53 back to top
  assets/css/app.scss
  assets/js/app.js
  assets/js/backToTop.js
  templates/_backToTop.html.twig
  templates/base.html.twig
  templates/layoutFront.html.twig
Labels: Conflicts, Review by PO

#85 SPRINT3US58
  assets/css/app.scss
  src/Controller/CommentAdminController.php
  templates/comment_admin/index.html.twig
  templates/comment_admin/show.html.twig
Labels: Correction Done, Review by PO

#86 Us57
  assets/css/app.scss
  assets/js/modal.js
  src/Controller/JobController.php
  src/Migrations/Version20181203142800.php
  src/Migrations/Version20181203160032.php
  templates/company/button_company.html.twig
  templates/job/show.html.twig
  templates/learning_center/button_learning_center.html.twig
Labels: Correction Done, Review by PO

#93 Sprint3 us56fix
  assets/css/app.scss
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  templates/learning_center_admin/show.html.twig
Labels: Review by PO

#55 S02 us45 add partner
  .gitignore
  assets/css/app.scss
  assets/js/app.js
  assets/js/previewUpload.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Migrations/Version20181203140652.php
  symfony.lock
  templates/partner/_form.html.twig
  templates/partner/new.html.twig
Labels: Correction Done, Review by PO

#94 Sprint03 fix dev lc admin controller
  src/Controller/LearningCenterAdminController.php
Labels: Review by PO

#88 Sprint3 us59julo
  assets/css/app.scss
  src/Controller/CompanyAdminController.php
  src/Controller/CompanyController.php
  src/Form/CompanyType.php
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company_admin/show.html.twig
Labels: Correction Done, Review by PO

#98 Sprint3us16
  src/Controller/CommentAdminController.php
  templates/comment_admin/_delete_form.html.twig
  templates/comment_admin/index.html.twig
  templates/comment_admin/show.html.twig
Labels: Review by PO

#101 Dev
  assets/css/app.scss
  src/Controller/CommentAdminController.php
  src/Controller/CompanyAdminController.php
  src/Controller/CompanyController.php
  src/Form/CompanyType.php
  templates/comment_admin/_delete_form.html.twig
  templates/comment_admin/index.html.twig
  templates/comment_admin/show.html.twig
  templates/company/_delete_form.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/company/new.html.twig
  templates/company_admin/show.html.twig
Labels: Review by PO

#102 SPRINT3US17
  src/Controller/CommentAdminController.php
  src/Form/AcceptType.php
  templates/comment_admin/_form_accepted.html.twig
  templates/comment_admin/show.html.twig
Labels: Review by PO

#100 S03 us12 add comment
  assets/css/app.scss
  assets/js/previewUpload.js
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Controller/CommentController.php
  src/Entity/Comment.php
  src/Form/CommentType.php
  templates/comment/_form.html.twig
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/job/show.html.twig
  templates/partner/new.html.twig
Labels: Correction Done, Review by PO

#99 S03 us19 list compagny
  assets/css/app.scss
  assets/images/logo.jpg
  src/Controller/CompanyAdminController.php
  src/Entity/Company.php
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/company_admin/index.html.twig
Labels: Correction Done, Review by PO

#96 Fix us44 slider partner
  .gitignore
  assets/css/app.scss
  assets/js/app.js
  assets/js/slider.js
  package.json
  public/images/.gitkeep
  src/Controller/HomeController.php
  symfony.lock
  templates/base.html.twig
  templates/home/index.html.twig
  templates/partner/_slider.html.twig
  yarn.lock
Labels: Correction Done, Review by PO

#105 FIX pour clean master avant mise en prod
  templates/comment_admin/index.html.twig
  templates/job/show.html.twig
  templates/learning_center_admin/index.html.twig
Labels: Review by PO

#106 fix backToTop and bg partner slider
  assets/css/app.scss
  src/Form/CommentType.php
  templates/_backToTop.html.twig
  templates/comment/_form.html.twig
  templates/home/index.html.twig
  templates/partner/_slider.html.twig
Labels: Review by PO

#104 S03 us08 form contact
  .env
  assets/css/app.scss
  assets/js/app.js
  assets/js/contact.js
  composer.json
  composer.lock
  config/services.yaml
  src/Controller/ContactFormController.php
  src/Entity/ContactForm.php
  src/Form/ContactFormType.php
  src/Repository/ContactFormRepository.php
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/contact/_form.html.twig
  templates/contact/indexContact.html.twig
  templates/contact/setBodyContact.html.twig
Labels: Correction Done

#103 Sprint3 fix scss us56 us59
  assets/css/app.scss
  templates/company_admin/show.html.twig
  templates/learning_center_admin/show.html.twig
Labels: Review by PO

#109 S03 Us28
  assets/css/app.scss
  assets/js/previewUpload.js
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Controller/JobAdminController.php
  src/Entity/Category.php
  src/Entity/Job.php
  src/Form/JobType.php
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/job_admin/index.html.twig
  templates/job_admin/new.html.twig
Labels: Correction Done, Review by PO

#110 changing mapping of comment
  src/Entity/Comment.php
Labels: Review by PO

#131 Sprint4 us36
  src/Controller/CompanyAdminController.php
  src/Form/CompanyType.php
  templates/company_admin/_delete_form.html.twig
  templates/company_admin/show.html.twig
Labels: Correction Done, Review by PO

#133 Sprint4 us39
  assets/css/app.scss
  src/Controller/LearningCenterAdminController.php
  templates/learning_center_admin/_delete_form.html.twig
  templates/learning_center_admin/index.html.twig
  templates/learning_center_admin/show.html.twig
Labels: Correction Done, Review by PO

#140 Dev
  assets/css/app.scss
  assets/js/previewUpload.js
  config/packages/vich_uploader.yaml
  config/services.yaml
  src/Controller/CompanyAdminController.php
  src/Controller/JobAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  src/Controller/PartnerController.php
  src/Entity/Category.php
  src/Entity/Comment.php
  src/Entity/Job.php
  src/Form/CompanyType.php
  src/Form/JobType.php
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/comment_admin/index.html.twig
  templates/comment_admin/show.html.twig
  templates/company_admin/_delete_form.html.twig
  templates/company_admin/show.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/job_admin/index.html.twig
  templates/job_admin/new.html.twig
  templates/learning_center_admin/_delete_form.html.twig
  templates/learning_center_admin/index.html.twig
  templates/learning_center_admin/show.html.twig
  templates/partner/new.html.twig
Labels: Review by PO

#111 Fix contact
  src/Form/ContactFormType.php
  templates/base.html.twig
  templates/contact/_form.html.twig
Labels: Correction Done, Review by PO

#136 Fix btn category
  assets/css/app.scss
  src/Entity/Category.php
  src/Form/CategoryType.php
  templates/category_admin/new.html.twig
Labels: Correction Done, Review by PO

#141 fix entity
  src/Entity/Company.php
Labels: Review by PO

#143 Fix route and title
  assets/css/app.scss
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/comment_admin/index.html.twig
  templates/company_admin/show.html.twig
  templates/contact/indexContact.html.twig
  templates/job/show.html.twig
  templates/learning_center_admin/index.html.twig
  templates/learning_center_admin/show.html.twig
  templates/partner/new.html.twig
Labels: Review by PO

#138 fix tiny int
  templates/company/button_company.html.twig
  templates/learning_center/button_learning_center.html.twig
Labels: Correction Done

#144 Sprint04 us21
  src/Controller/LearningCenterAdminController.php
  src/Form/AcceptLearningCenterType.php
  templates/learning_center_admin/_form_accepted.html.twig
  templates/learning_center_admin/show.html.twig
Labels: Review by PO

#142 Sprint4 us22
  src/Controller/CompanyAdminController.php
  src/Form/AcceptCompanyType.php
  templates/company_admin/_form_accepted.html.twig
  templates/company_admin/show.html.twig
Labels: Correction Done, Review by PO

#145 Us27 dashboard
  assets/css/app.scss
  src/Controller/HomeAdminController.php
  templates/home_admin/index.html.twig
Labels: Correction Done, Review by PO

#137 Sprint4 us4
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Review by PO

#132 Us13 show categories
  assets/css/app.scss
  assets/images/front-end.jpg
  assets/js/slider.js
  src/Controller/JobController.php
  src/Entity/Category.php
  src/Entity/Job.php
  templates/job/index.html.twig
Labels: Review by PO

#146 Fix dev 13/12
  config/packages/vich_uploader.yaml
  templates/contact/_form.html.twig
  templates/home_admin/index.html.twig
  templates/job/index.html.twig
Labels: Correction Done, Review by PO

#152 Sprint05 us62
  src/Controller/CategoryAdminController.php
  templates/category_admin/index.html.twig
Labels: Review by PO

#167 fix img comment
  assets/css/app.scss
  templates/comment_admin/show.html.twig
  templates/job/show.html.twig
Labels: Review by PO

#168 US 64 swiftmailer (email envoyé à l'expéditeur)
  src/Controller/ContactFormController.php
Labels: Review by PO

#157 Sprint04 us34
  assets/css/app.scss
  assets/js/previewUpload.js
  config/packages/vich_uploader.yaml
  src/Controller/CompanyAdminController.php
  src/Entity/Company.php
  src/Form/CompanyType.php
  templates/company/button_company.html.twig
  templates/company_admin/_form.html.twig
  templates/company_admin/index.html.twig
  templates/company_admin/new.html.twig
  templates/company_admin/show.html.twig
Labels: Correction Done, Review by PO

#169 Sprint5 us63 julo
  src/Controller/CategoryAdminController.php
  templates/category_admin/index.html.twig
  templates/category_admin/show.html.twig
Labels: Review by PO

#172 US42 pagination organisme
  assets/css/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yaml
  src/Controller/LearningCenterAdminController.php
  symfony.lock
  templates/learning_center_admin/index.html.twig
  translations/KnpPaginatorBundle.yml
Labels: Conflicts
