Repository WildCodeSchool/orleans-0918-php-metiers-du-numerique, pull requests merged in 2018-11, with the labels that each got.

#10 Add webpack
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  webpack.config.js
  yarn.lock
Labels: Review by PO

#11 Sprint1 us9
  .gitignore
  .travis.yml
  assets/css/app.scss
  assets/images/backend.png
  assets/js/app.js
  composer.lock
  package.json
  src/Controller/JobController.php
  src/Entity/Job.php
  src/Form/JobType.php
  src/Migrations/Version20181121095902.php
  src/Migrations/Version20181121103930.php
  src/Migrations/Version20181122155201.php
  src/Repository/JobRepository.php
  templates/base.html.twig
  templates/job/_delete_form.html.twig
  templates/job/_form.html.twig
  templates/job/edit.html.twig
  templates/job/index.html.twig
  templates/job/new.html.twig
  templates/job/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Correction Done

#13 Travis change requested done
  src/Repository/JobRepository.php
Labels: Review by PO

#18 page home, partie 'notre concept'
  assets/css/app.scss
  src/Controller/HomeController.php
  templates/home/index.html.twig
Labels: Review by PO

#14 S1 us44 partner slider
  assets/css/app.scss
  assets/js/app.js
  assets/js/onScroll.js
  composer.lock
  package.json
  src/Controller/HomeController.php
  src/Controller/PartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Migrations/Version20181122181103.php
  src/Repository/PartnerRepository.php
  templates/base.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
  templates/layout.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/_form.html.twig
  templates/partner/_slider.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/new.html.twig
  templates/partner/show.html.twig
  yarn.lock
Labels: Correction Done, Review by PO

#20 Dev
  assets/css/app.scss
  assets/js/app.js
  assets/js/onScroll.js
  composer.lock
  package.json
  src/Controller/HomeController.php
  src/Controller/PartnerController.php
  src/Entity/Partner.php
  src/Form/PartnerType.php
  src/Migrations/Version20181122181103.php
  src/Repository/PartnerRepository.php
  templates/base.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
  templates/layout.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/_form.html.twig
  templates/partner/_slider.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/new.html.twig
  templates/partner/show.html.twig
  yarn.lock
Labels: Review by PO

#15 S01 us1 navbar
  assets/css/app.scss
  assets/js/app.js
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/job/index.html.twig
  templates/layoutFront.html.twig
  webpack.config.js
Labels: Correction Done, Review by PO

#19 Sprint01 us31
  assets/css/app.scss
  config/packages/twig.yaml
  package-lock.json
  src/Controller/CategoryAdminController.php
  src/Controller/CategoryController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  src/Migrations/Version20181122183247.php
  src/Repository/CategoryRepository.php
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/show.html.twig
  templates/category_admin/new.html.twig
  templates/layoutAdmin.html.twig
Labels: Correction Done, Review by PO

#16 Us52 banner
  assets/css/app.scss
  assets/images/server.jpg
  assets/js/app.js
  assets/js/onScroll.js
  templates/_banner.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
  templates/layout.html.twig
  templates/layoutFront.html.twig
  webpack.config.js
Labels: Conflicts

#42 Dev
  assets/css/app.scss
  assets/images/server.jpg
  assets/js/app.js
  assets/js/onScroll.js
  config/packages/twig.yaml
  package-lock.json
  src/Controller/CategoryAdminController.php
  src/Controller/CategoryController.php
  src/Entity/Category.php
  src/Form/CategoryType.php
  src/Migrations/Version20181122183247.php
  src/Repository/CategoryRepository.php
  templates/_banner.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/show.html.twig
  templates/category_admin/new.html.twig
  templates/home/index.html.twig
  templates/job/index.html.twig
  templates/job/show.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  templates/layoutFront.html.twig
  webpack.config.js
Labels: Review by PO

#43 S02 us40 navbar admin
  templates/_navbarAdmin.html.twig
  templates/layoutAdmin.html.twig
Labels: Review by PO

#44 SPRINT2 US 15
  assets/css/app.scss
  src/Controller/CommentAdminController.php
  src/Controller/CommentController.php
  src/Entity/Comment.php
  src/Entity/Job.php
  src/Form/CommentType.php
  src/Migrations/Version20181127102743.php
  src/Migrations/Version20181127103703.php
  src/Migrations/Version20181128104618.php
  src/Migrations/Version20181128173743.php
  src/Repository/CommentRepository.php
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/comment/show.html.twig
  templates/comment_admin/index.html.twig
Labels: Correction Done, Review by PO

#46 fixed container stuff and changing css of footer after update with th…
  assets/css/app.scss
  templates/_footer.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
Labels: Correction Done, Review by PO

#53 Fix psr
  .travis.yml
  composer.lock
  src/Controller/CategoryAdminController.php
  src/Controller/CommentAdminController.php
  symfony.lock
Labels: Review by PO

#50 Dev to master
  .travis.yml
  assets/css/app.scss
  composer.lock
  src/Controller/CategoryAdminController.php
  src/Controller/CommentAdminController.php
  src/Controller/CommentController.php
  src/Entity/Comment.php
  src/Entity/Job.php
  src/Form/CommentType.php
  src/Migrations/Version20181127102743.php
  src/Migrations/Version20181127103703.php
  src/Migrations/Version20181128104618.php
  src/Migrations/Version20181128173743.php
  src/Repository/CommentRepository.php
  symfony.lock
  templates/_footer.html.twig
  templates/_navbarAdmin.html.twig
  templates/base.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/new.html.twig
  templates/comment/show.html.twig
  templates/comment_admin/index.html.twig
  templates/home/index.html.twig
  templates/job/show.html.twig
  templates/layoutAdmin.html.twig
  templates/layoutFront.html.twig
Labels: Review by PO

#54 Sprint2 us11
  assets/css/app.scss
  composer.json
  composer.lock
  src/Controller/JobController.php
  symfony.lock
  templates/job/show.html.twig
Labels: Review by PO

#49 Us54 modal company (thomas)
  assets/css/app.scss
  assets/js/app.js
  assets/js/modal.js
  src/Controller/JobController.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Migrations/Version20181129091739.php
  src/Migrations/Version20181129163711.php
  src/Repository/CompanyRepository.php
  templates/company/button_company.html.twig
  templates/job/show.html.twig
  yarn.lock
Labels: Correction Done, Review by PO

#57 Dev
  assets/css/app.scss
  assets/js/app.js
  assets/js/modal.js
  composer.json
  composer.lock
  src/Controller/JobController.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Migrations/Version20181129091739.php
  src/Migrations/Version20181129163711.php
  src/Repository/CompanyRepository.php
  symfony.lock
  templates/company/button_company.html.twig
  templates/job/show.html.twig
  yarn.lock
Labels: Review by PO
