Repository WildCodeSchool/orleans-0918-php-metiers-du-numerique, pull requests merged in 2019-01, with the labels that each got.

#183 Dev ( en priorité )
  assets/css/app.scss
  assets/js/previewUpload.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_paginator.yaml
  config/packages/vich_uploader.yaml
  src/Controller/CategoryAdminController.php
  src/Controller/CompanyAdminController.php
  src/Controller/ContactFormController.php
  src/Controller/LearningCenterAdminController.php
  src/Entity/Company.php
  src/Form/CompanyType.php
  symfony.lock
  templates/category_admin/index.html.twig
  templates/category_admin/show.html.twig
  templates/comment_admin/show.html.twig
  templates/company/button_company.html.twig
  templates/company_admin/_form.html.twig
  templates/company_admin/index.html.twig
  templates/company_admin/new.html.twig
  templates/company_admin/show.html.twig
  templates/job/show.html.twig
  templates/learning_center_admin/index.html.twig
  translations/KnpPaginatorBundle.yml
Labels: Review by PO

#177 desolé pour le vardump
  src/Controller/ContactFormController.php
Labels: Review by PO

#173 US43 pagination entreprise
  src/Controller/CompanyAdminController.php
  templates/company_admin/index.html.twig
Labels: Correction Done, Review by PO

#174 US65 pagination commentaire
  src/Controller/CommentAdminController.php
  templates/comment_admin/index.html.twig
Labels: Correction Done, Review by PO

#184 Fix partie admin
  assets/css/app.scss
  templates/comment_admin/index.html.twig
  templates/company_admin/index.html.twig
  templates/learning_center_admin/index.html.twig
  templates/partner/new.html.twig
Labels: Review by PO

#186 Sprint06 us35
  src/Controller/CompanyAdminController.php
  src/Entity/Company.php
  templates/company_admin/_form.html.twig
  templates/company_admin/edit.html.twig
  templates/company_admin/index.html.twig
Labels: Review by PO

#188 Fix nav footer
  assets/css/app.scss
Labels: Review by PO

#189 fix comment
  src/Entity/Comment.php
Labels: Review by PO

#191 Drop db
  src/Migrations/Version20181128091914.php
  src/Migrations/Version20181203140652.php
  src/Migrations/Version20181203142800.php
  src/Migrations/Version20181203160032.php
  src/Migrations/Version20181204093310.php
  src/Migrations/Version20181210152440.php
  src/Migrations/Version20190104150902.php
Labels: Review by PO

#149 Badge panel admin
  assets/css/app.scss
  src/Controller/HomeAdminController.php
  src/Repository/CommentRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/LearningCenterRepository.php
  templates/home_admin/index.html.twig
Labels: Review by PO

#193 Fix accueil
  .gitignore
  composer.json
  composer.lock
  symfony.lock
  templates/home/index.html.twig
Labels: Review by PO

#214 Index partner done
  src/Controller/PartnerAdminController.php
  templates/partner_admin/index.html.twig
Labels: Review by PO

#216 ajout message flash et fix form partnaire
  src/Controller/CompanyAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/PartnerController.php
  src/Form/CompanyType.php
Labels: Review by PO

#217 Sprint7 us65
  src/Controller/JobAdminController.php
  templates/home_admin/index.html.twig
  templates/job_admin/index.html.twig
Labels: Review by PO

#219 fix lien nav admin
  templates/_navbarAdmin.html.twig
Labels: Review by PO

#220 vich fix
  src/Form/CommentType.php
  src/Form/JobType.php
  src/Form/PartnerType.php
Labels: Review by PO

#222 fix home
  templates/home/index.html.twig
Labels: Review by PO

#221 Dev to master apres le fix home
  assets/css/app.scss
  src/Controller/CompanyAdminController.php
  src/Controller/HomeAdminController.php
  src/Controller/JobAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/PartnerAdminController.php
  src/Controller/PartnerController.php
  src/Entity/Category.php
  src/Entity/LearningCenter.php
  src/Form/CommentType.php
  src/Form/CompanyType.php
  src/Form/JobType.php
  src/Form/LearningCenterType.php
  src/Form/PartnerType.php
  src/Repository/CommentRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/LearningCenterRepository.php
  templates/_navbarAdmin.html.twig
  templates/home/index.html.twig
  templates/home_admin/index.html.twig
  templates/job_admin/index.html.twig
  templates/learning_center/edit.html.twig
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/edit.html.twig
  templates/learning_center_admin/index.html.twig
  templates/partner_admin/index.html.twig
Labels: Review by PO

#187 Sprint06 us60
  assets/js/app.js
  assets/js/showMore.js
  src/Controller/JobController.php
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
Labels: Correction Done, Review by PO

#225 Sprint7 fix nav admin
  templates/_navbarAdmin.html.twig
Labels: Review by PO

#226 Sprint07 us68
  src/Controller/JobAdminController.php
  src/Entity/Job.php
  templates/job_admin/_form.html.twig
  templates/job_admin/edit.html.twig
  templates/job_admin/index.html.twig
Labels: Review by PO

#230 fix navbar dropdown and spypage
  assets/css/app.scss
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/company/new.html.twig
  templates/learning_center/new.html.twig
Labels: Review by PO

#231 Fix default picture
  assets/images/defaultjobpicture.png
  assets/images/defaultpicture.png
  src/Entity/Comment.php
  src/Entity/Company.php
  src/Form/CommentType.php
  src/Form/CompanyType.php
  templates/comment/_form.html.twig
  templates/company_admin/_form.html.twig
Labels: Review by PO

#227 Sprint07 us06
  src/Controller/CompanyController.php
  src/Entity/Company.php
  templates/company/_form.html.twig
  templates/company/new.html.twig
Labels: Correction Done

#232 fix badges admin
  src/Controller/HomeAdminController.php
  src/Repository/CommentRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/LearningCenterRepository.php
Labels: Correction Done, Review by PO

#229 SPRINT07US69
  assets/css/app.scss
  src/Controller/JobAdminController.php
  templates/job/_delete_form.html.twig
  templates/job_admin/_delete_form.html.twig
  templates/job_admin/index.html.twig
Labels: Correction Done, Review by PO

#234 add videoTitle in newJobForm
  src/Form/JobType.php
  templates/job_admin/_form.html.twig
Labels: Review by PO

#233 Make fixture
  composer.json
  composer.lock
  config/bundles.php
  src/DataFixtures/AdminFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/JobFixtures.php
  src/DataFixtures/LearningCenterFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Comment.php
  src/Entity/Company.php
  src/Entity/LearningCenter.php
  src/Entity/Partner.php
  symfony.lock
Labels: Correction Done, Review by PO

#235 le fix de l'Unique Caractère
  config/services.yaml
  src/Controller/CompanyAdminController.php
  src/Controller/LearningCenterAdminController.php
Labels: Review by PO

#236 Fix index adminjob
  src/Controller/JobAdminController.php
  src/Entity/Job.php
  templates/job_admin/index.html.twig
Labels: Review by PO

#240 Dev to master avant les autre PR
  assets/css/app.scss
  assets/images/defaultjobpicture.png
  assets/images/defaultpicture.png
  assets/js/app.js
  assets/js/showMore.js
  composer.json
  composer.lock
  config/bundles.php
  config/services.yaml
  src/Controller/CompanyAdminController.php
  src/Controller/CompanyController.php
  src/Controller/HomeAdminController.php
  src/Controller/JobAdminController.php
  src/Controller/JobController.php
  src/Controller/LearningCenterAdminController.php
  src/DataFixtures/AdminFixtures.php
  src/DataFixtures/CategoryFixtures.php
  src/DataFixtures/CommentFixtures.php
  src/DataFixtures/CompanyFixtures.php
  src/DataFixtures/JobFixtures.php
  src/DataFixtures/LearningCenterFixtures.php
  src/DataFixtures/PartnerFixtures.php
  src/Entity/Comment.php
  src/Entity/Company.php
  src/Entity/Job.php
  src/Entity/LearningCenter.php
  src/Entity/Partner.php
  src/Form/CommentType.php
  src/Form/CompanyType.php
  src/Form/JobType.php
  src/Repository/CommentRepository.php
  src/Repository/CompanyRepository.php
  src/Repository/LearningCenterRepository.php
  symfony.lock
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/comment/_form.html.twig
  templates/company/_form.html.twig
  templates/company/new.html.twig
  templates/company_admin/_form.html.twig
  templates/job/_delete_form.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  templates/job_admin/_delete_form.html.twig
  templates/job_admin/_form.html.twig
  templates/job_admin/edit.html.twig
  templates/job_admin/index.html.twig
  templates/learning_center/new.html.twig
Labels: Review by PO

#228 Sprint07 us07
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  src/Entity/LearningCenter.php
  src/Form/LearningCenterType.php
  templates/learning_center/_form.html.twig
  templates/learning_center/new.html.twig
Labels: Review by PO

#237 pagination job
  src/Controller/JobAdminController.php
  templates/job_admin/index.html.twig
Labels: Review by PO

#238 pagination partner
  src/Controller/PartnerAdminController.php
  templates/partner_admin/index.html.twig
Labels: Review by PO

#239 pagination category
  src/Controller/CategoryAdminController.php
  templates/category_admin/index.html.twig
Labels: Review by PO

#241 Fix redirection
  src/Controller/CategoryAdminController.php
  src/Controller/JobAdminController.php
  src/Controller/PartnerAdminController.php
  src/Controller/PartnerController.php
Labels: Review by PO

#243 Fix navbar
  templates/_navbar.html.twig
  templates/home/index.html.twig
Labels: Review by PO

#244 fix Btn job to category
  templates/category_admin/index.html.twig
  templates/job_admin/index.html.twig
Labels: Review by PO

#249 Fix style btn
  assets/css/app.scss
Labels: Review by PO

#250 Sprint07 us71
  src/Controller/CompanyAdminController.php
Labels: Review by PO

#252 Sprint07 us70
  src/Controller/CommentAdminController.php
Labels: Correction Done, Review by PO

#253 fix affichage loupe
  assets/css/app.scss
  templates/_navbar.html.twig
Labels: Review by PO

#255 Dev to master
  assets/css/app.scss
  src/Controller/CategoryAdminController.php
  src/Controller/CommentAdminController.php
  src/Controller/CompanyAdminController.php
  src/Controller/JobAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  src/Controller/PartnerAdminController.php
  src/Controller/PartnerController.php
  src/Entity/LearningCenter.php
  src/Form/LearningCenterType.php
  templates/_navbar.html.twig
  templates/category_admin/index.html.twig
  templates/home/index.html.twig
  templates/job_admin/index.html.twig
  templates/learning_center/_form.html.twig
  templates/learning_center/new.html.twig
  templates/partner_admin/index.html.twig
Labels: Review by PO

#248 Fix new category btn
  src/Controller/CategoryAdminController.php
  templates/category_admin/index.html.twig
  templates/category_admin/new.html.twig
Labels: Correction Done, Review by PO

#257 Sprint7 fix nav
  templates/_navbar.html.twig
Labels: Review by PO

#254 Us10 addlike
  assets/css/app.scss
  assets/js/add-like.js
  assets/js/app.js
  composer.lock
  config/packages/vich_uploader.yaml
  src/Controller/CommentController.php
  src/Controller/JobController.php
  src/Form/CommentType.php
  src/Form/PartnerType.php
  templates/comment/_like.html.twig
  templates/comment_admin/show.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
Labels: Correction Done, Review by PO

#259 Sprint07 addcompanie
  assets/css/app.scss
  assets/js/app.js
  assets/js/mySelect2.js
  package.json
  src/Form/CompanyType.php
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/new.html.twig
  webpack.config.js
  yarn.lock
Labels: Correction Done, Review by PO

#262 Dev
  assets/css/app.scss
  assets/js/add-like.js
  assets/js/app.js
  assets/js/mySelect2.js
  composer.lock
  config/packages/vich_uploader.yaml
  package.json
  src/Controller/CategoryAdminController.php
  src/Controller/CommentController.php
  src/Controller/JobController.php
  src/Form/CommentType.php
  src/Form/CompanyType.php
  src/Form/PartnerType.php
  templates/_navbar.html.twig
  templates/category_admin/index.html.twig
  templates/category_admin/new.html.twig
  templates/comment/_like.html.twig
  templates/comment_admin/show.html.twig
  templates/company/_form.html.twig
  templates/company/edit.html.twig
  templates/company/new.html.twig
  templates/company_admin/index.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  webpack.config.js
  yarn.lock
Labels: Review by PO

#258 Fix category
  assets/css/app.scss
  templates/job/_card.html.twig
  templates/job/index.html.twig
Labels: Correction Done, Review by PO

#261 Sprint6 us32
  assets/css/app.scss
  src/Controller/CategoryAdminController.php
  templates/category_admin/_delete_form.html.twig
  templates/category_admin/index.html.twig
  templates/category_admin/show.html.twig
Labels: Review by PO

#264 Fix navbar routes
  templates/_navbar.html.twig
Labels: Review by PO

#265 hidden phone device
  templates/_backToTop.html.twig
Labels: Review by PO

#260 Fix placeholder to vich upload
  src/Entity/Job.php
  src/Entity/Partner.php
  src/Form/JobType.php
  src/Form/PartnerType.php
  templates/comment_admin/show.html.twig
  templates/company/_form.html.twig
  templates/company/button_company.html.twig
  templates/company_admin/show.html.twig
  templates/job/_card.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/show.html.twig
  templates/partner/_form.html.twig
  templates/partner/_slider.html.twig
Labels: Correction Done, Review by PO

#266 mise en forme add learningcenter user
  src/Form/LearningCenterType.php
  templates/learning_center/_form.html.twig
  templates/learning_center/new.html.twig
Labels: Review by PO

#267 mise en forme add companies Admin
  templates/company_admin/_form.html.twig
  templates/company_admin/edit.html.twig
  templates/company_admin/new.html.twig
Labels: Review by PO

#269 suppression et modification vue inutile
  src/Controller/CategoryController.php
  src/Controller/CommentController.php
  src/Controller/CompanyController.php
  src/Controller/JobController.php
  src/Controller/LearningCenterController.php
  src/Controller/PartnerAdminController.php
  src/Controller/PartnerController.php
  templates/category/_delete_form.html.twig
  templates/category/_form.html.twig
  templates/category/edit.html.twig
  templates/category/index.html.twig
  templates/category/show.html.twig
  templates/comment/_delete_form.html.twig
  templates/comment/edit.html.twig
  templates/comment/index.html.twig
  templates/comment/show.html.twig
  templates/company/_delete_form.html.twig
  templates/company/edit.html.twig
  templates/company/index.html.twig
  templates/job/_form.html.twig
  templates/job/edit.html.twig
  templates/job/new.html.twig
  templates/learning_center/_delete_form.html.twig
  templates/learning_center/index.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner/edit.html.twig
  templates/partner/index.html.twig
  templates/partner/show.html.twig
  templates/partner_admin/_form.html.twig
  templates/partner_admin/new.html.twig
Labels: Correction Done

#270 correction done
  templates/contact/indexContact.html.twig
Labels: Review by PO

#271 fix_comment
  templates/comment/new.html.twig
Labels: Review by PO

#272 Fix index
  assets/css/app.scss
  src/Controller/PartnerAdminController.php
  templates/category_admin/new.html.twig
  templates/company/button_company.html.twig
  templates/contact/_form.html.twig
  templates/job/_card.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner_admin/index.html.twig
Labels: Correction Done, Review by PO

#274 Sprint07 add learningcenter admin
  src/Controller/LearningCenterAdminController.php
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/edit.html.twig
  templates/learning_center_admin/new.html.twig
Labels: Review by PO

#279 ajout message flash
  src/Controller/CategoryAdminController.php
  src/Controller/CommentAdminController.php
  src/Controller/CommentController.php
  src/Controller/CompanyAdminController.php
  src/Controller/CompanyController.php
  src/Controller/JobAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  src/Controller/PartnerAdminController.php
Labels: Review by PO

#276 Fix asterisk formulaire
  templates/comment/_form.html.twig
  templates/company/_form.html.twig
  templates/company_admin/_form.html.twig
  templates/contact/_form.html.twig
  templates/job_admin/_form.html.twig
  templates/partner_admin/_form.html.twig
Labels: Review by PO

#277 responsive back-to-top
  assets/css/app.scss
  templates/_backToTop.html.twig
Labels: Review by PO

#278 ajustement and fix images
  assets/css/app.scss
  templates/comment/_like.html.twig
  templates/job/loadComment.html.twig
Labels: Review by PO

#281 add arrow
  templates/comment_admin/show.html.twig
  templates/company_admin/show.html.twig
  templates/learning_center_admin/show.html.twig
Labels: Review by PO

#283 modal responsive
  templates/company/button_company.html.twig
  templates/job/show.html.twig
  templates/learning_center/button_learning_center.html.twig
Labels: Review by PO

#282 fix_title_video
  templates/job/show.html.twig
Labels: Review by PO

#284 ajout margin
  templates/home/index.html.twig
Labels: Review by PO

#285 Dev
  assets/css/app.scss
  src/Controller/CategoryAdminController.php
  src/Controller/CommentAdminController.php
  src/Controller/CommentController.php
  src/Controller/CompanyAdminController.php
  src/Controller/CompanyController.php
  src/Controller/JobAdminController.php
  src/Controller/LearningCenterAdminController.php
  src/Controller/LearningCenterController.php
  src/Controller/PartnerAdminController.php
  templates/_backToTop.html.twig
  templates/comment/_form.html.twig
  templates/comment/_like.html.twig
  templates/comment_admin/show.html.twig
  templates/company/_form.html.twig
  templates/company/button_company.html.twig
  templates/company_admin/_form.html.twig
  templates/company_admin/show.html.twig
  templates/contact/_form.html.twig
  templates/home/index.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/edit.html.twig
  templates/learning_center_admin/new.html.twig
  templates/learning_center_admin/show.html.twig
  templates/partner_admin/_form.html.twig
Labels: Review by PO

#287 Dev
  assets/css/app.scss
  templates/_navbar.html.twig
  templates/_searchmodal.html.twig
Labels: Review by PO

#292 Fix migration
  src/Migrations/Version20190111135951.php
Labels: Review by PO

#288 Fix home w3c
  templates/_backToTop.html.twig
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/base.html.twig
  templates/home/index.html.twig
Labels: Review by PO

#290 Fix form w3c
  src/Form/LearningCenterType.php
  templates/learning_center/_form.html.twig
Labels: Review by PO

#291 Fix form company
  src/Form/CompanyType.php
  templates/company/_form.html.twig
Labels: Review by PO

#294 index job w3c
  templates/job_admin/index.html.twig
Labels: Review by PO

#296 Fix w3 c job utilisateur
  templates/comment_admin/show.html.twig
  templates/company/button_company.html.twig
  templates/company_admin/show.html.twig
  templates/job/show.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/learning_center_admin/show.html.twig
Labels: Review by PO

#297 index partner w3c
  templates/partner_admin/index.html.twig
Labels: Review by PO

#299 fix
  templates/category_admin/_delete_form.html.twig
  templates/category_admin/index.html.twig
  templates/category_admin/show.html.twig
  templates/partner/_delete_form.html.twig
Labels: Review by PO

#298 Fix admin
  src/Form/CompanyType.php
  src/Form/LearningCenterType.php
  templates/_navbarAdmin.html.twig
  templates/company_admin/_form.html.twig
  templates/company_admin/index.html.twig
  templates/company_admin/new.html.twig
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/index.html.twig
  templates/learning_center_admin/new.html.twig
Labels: Correction Done, Review by PO

#300 Change label nex
  templates/partner_admin/_form.html.twig
  webpack.config.js
Labels: Review by PO

#304 fix css modal
  assets/css/app.scss
Labels: Review by PO

#305 Dev
  assets/css/app.scss
  src/Form/CommentType.php
  src/Form/CompanyType.php
  src/Form/JobType.php
  src/Form/LearningCenterType.php
  templates/_backToTop.html.twig
  templates/_footer.html.twig
  templates/_navbar.html.twig
  templates/_navbarAdmin.html.twig
  templates/base.html.twig
  templates/category_admin/_delete_form.html.twig
  templates/category_admin/index.html.twig
  templates/category_admin/show.html.twig
  templates/comment/_form.html.twig
  templates/comment_admin/show.html.twig
  templates/company/_form.html.twig
  templates/company/button_company.html.twig
  templates/company_admin/_form.html.twig
  templates/company_admin/index.html.twig
  templates/company_admin/new.html.twig
  templates/company_admin/show.html.twig
  templates/home/index.html.twig
  templates/job/search.html.twig
  templates/job/show.html.twig
  templates/job_admin/index.html.twig
  templates/learning_center/_form.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/learning_center_admin/_form.html.twig
  templates/learning_center_admin/index.html.twig
  templates/learning_center_admin/new.html.twig
  templates/learning_center_admin/show.html.twig
  templates/partner/_delete_form.html.twig
  templates/partner_admin/_form.html.twig
  templates/partner_admin/index.html.twig
Labels: Review by PO

#306 Entity mentions
  assets/css/app.scss
  assets/js/app.js
  assets/js/summernote.js
  package.json
  src/Controller/LegalNoticeController.php
  src/Entity/LegalNotice.php
  src/Form/LegalNoticeType.php
  src/Migrations/Version20190114151409.php
  src/Repository/LegalNoticeRepository.php
  templates/_footer.html.twig
  templates/_navbarAdmin.html.twig
  templates/legal_notice/index.html.twig
  templates/legal_notice_admin/_form.html.twig
  templates/legal_notice_admin/edit.html.twig
  templates/legal_notice_admin/index.html.twig
  yarn.lock
Labels: Correction Done, Review by PO

#308 Dev
  assets/css/app.scss
  assets/js/app.js
  assets/js/summernote.js
  package.json
  src/Controller/LegalNoticeController.php
  src/Entity/LegalNotice.php
  src/Form/LegalNoticeType.php
  src/Migrations/Version20190114151409.php
  src/Repository/LegalNoticeRepository.php
  templates/_footer.html.twig
  templates/_navbarAdmin.html.twig
  templates/legal_notice/index.html.twig
  templates/legal_notice_admin/_form.html.twig
  templates/legal_notice_admin/edit.html.twig
  templates/legal_notice_admin/index.html.twig
  yarn.lock
Labels: Review by PO

#309 Fix commentaire
  templates/job/loadComment.html.twig
Labels: Review by PO

#311 fix vich job
  src/Entity/Job.php
  src/Migrations/Version20190116102901.php
Labels: Review by PO

#312 Mise en forme de la description des fiches metiers + bouton aligner
  assets/css/app.scss
  templates/job/show.html.twig
Labels: Review by PO

#313 Dev
  assets/css/app.scss
  src/Entity/Job.php
  src/Migrations/Version20190116102901.php
  templates/job/show.html.twig
Labels: Review by PO

#314 Add summernote job
  assets/css/app.scss
  src/Form/JobType.php
  templates/job/_card.html.twig
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/job_admin/index.html.twig
Labels: Review by PO

#316 Suppression des espaces dans les src + l'optimisation de l'asset vich
  templates/company/button_company.html.twig
  templates/job/_card.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/partner/_slider.html.twig
Labels: Correction Done, Review by PO

#317 Dev
  assets/css/app.scss
  src/Form/JobType.php
  templates/company/button_company.html.twig
  templates/job/_card.html.twig
  templates/job/loadComment.html.twig
  templates/job/show.html.twig
  templates/job_admin/_form.html.twig
  templates/job_admin/index.html.twig
  templates/learning_center/button_learning_center.html.twig
  templates/partner/_slider.html.twig
Labels: Review by PO

#318 fix swiftmailer
  src/Entity/ContactForm.php
  src/Migrations/Version20190124124940.php
Labels: Review by PO

#319 Fix log admin
  src/Security/AppAuthenticator.php
Labels: Review by PO

#320 target=blank sur les liens
  templates/_footer.html.twig
  templates/partner/_slider.html.twig
Labels: Review by PO

#321 add texte concept, modif fautes footers
  templates/_footer.html.twig
  templates/home/index.html.twig
Labels: Review by PO

#322 Dev
  src/Entity/ContactForm.php
  src/Migrations/Version20190124124940.php
  src/Security/AppAuthenticator.php
  templates/_footer.html.twig
  templates/home/index.html.twig
  templates/partner/_slider.html.twig
Labels: Review by PO
